name: Publish public/ to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-public:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add assetlinks.json if provided
        if: ${{ secrets.ASSETLINKS_JSON != '' }}
        run: |
          echo 'Adding assetlinks.json from secret to public/.well-known'
          mkdir -p public/.well-known
          printf "%s" "${{ secrets.ASSETLINKS_JSON }}" > public/.well-known/assetlinks.json

      - name: Deploy public to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
